// Code generated by "stringer -type=Keyword"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALGORITMO-0]
	_ = x[FINALGORITMO-1]
	_ = x[ESCRIBIR-2]
	_ = x[LEER-3]
	_ = x[MOD-4]
}

const _Keyword_name = "ALGORITMOFINALGORITMOESCRIBIRLEERMOD"

var _Keyword_index = [...]uint8{0, 9, 21, 29, 33, 36}

func (i Keyword) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Keyword_index)-1 {
		return "Keyword(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Keyword_name[_Keyword_index[idx]:_Keyword_index[idx+1]]
}
