// Code generated by "stringer -type=Keyword"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALGORITMO-0]
	_ = x[FINALGORITMO-1]
	_ = x[ESCRIBIR-2]
	_ = x[LEER-3]
	_ = x[MOD-4]
	_ = x[SI-5]
	_ = x[ENTONCES-6]
	_ = x[SINO-7]
	_ = x[FINSI-8]
	_ = x[DEFINIR-9]
	_ = x[COMO-10]
	_ = x[ENTERO-11]
	_ = x[CADENA-12]
	_ = x[LOGICO-13]
	_ = x[REAL-14]
	_ = x[MIENTRAS-15]
	_ = x[HACER-16]
	_ = x[FINMIENTRAS-17]
	_ = x[BORRAR-18]
	_ = x[PANTALLA-19]
}

const _Keyword_name = "ALGORITMOFINALGORITMOESCRIBIRLEERMODSIENTONCESSINOFINSIDEFINIRCOMOENTEROCADENALOGICOREALMIENTRASHACERFINMIENTRASBORRARPANTALLA"

var _Keyword_index = [...]uint8{0, 9, 21, 29, 33, 36, 38, 46, 50, 55, 62, 66, 72, 78, 84, 88, 96, 101, 112, 118, 126}

func (i Keyword) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Keyword_index)-1 {
		return "Keyword(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Keyword_name[_Keyword_index[idx]:_Keyword_index[idx+1]]
}
