// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KEYWORD-0]
	_ = x[IDENTIFIER-1]
	_ = x[STRING_LITERAL-2]
	_ = x[NUMBER_LITERAL-3]
	_ = x[BOOLEAN_LITERAL-4]
	_ = x[EOF-5]
}

const _TokenType_name = "KEYWORDIDENTIFIERSTRING_LITERALNUMBER_LITERALBOOLEAN_LITERALEOF"

var _TokenType_index = [...]uint8{0, 7, 17, 31, 45, 60, 63}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
