// Code generated by "stringer -type=TokenType internal/lexer/token.go"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KEYWORD-0]
	_ = x[IDENTIFIER-1]
	_ = x[STRING_LITERAL-2]
	_ = x[NUMBER_LITERAL-3]
	_ = x[BOOLEAN_LITERAL-4]
	_ = x[DOT-5]
	_ = x[COMMA-6]
	_ = x[EQUALS-7]
	_ = x[L_PARENTHESES-8]
	_ = x[R_PARENTHESES-9]
	_ = x[L_BRACKET-10]
	_ = x[R_BRACKET-11]
	_ = x[COLON-12]
	_ = x[PLUS-13]
	_ = x[MINUS-14]
	_ = x[ASTERISK-15]
	_ = x[SLASH-16]
	_ = x[L_ANGLE-17]
	_ = x[R_ANGLE-18]
	_ = x[AMPERSAND-19]
	_ = x[PIPE-20]
	_ = x[EX_MARK-21]
	_ = x[NEWLINE-22]
	_ = x[EOF-23]
}

const _TokenType_name = "KEYWORDIDENTIFIERSTRING_LITERALNUMBER_LITERALBOOLEAN_LITERALDOTCOMMAEQUALSL_PARENTHESESR_PARENTHESESL_BRACKETR_BRACKETCOLONPLUSMINUSASTERISKSLASHL_ANGLER_ANGLEAMPERSANDPIPEEX_MARKNEWLINEEOF"

var _TokenType_index = [...]uint8{0, 7, 17, 31, 45, 60, 63, 68, 74, 87, 100, 109, 118, 123, 127, 132, 140, 145, 152, 159, 168, 172, 179, 186, 189}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
